import io
import re
from typing import List, Dict, Any, Optional
from datetime import datetime

# Attempt document generator imports
try:
    import docx
    from docx.shared import Pt, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
except ImportError:
    docx = None

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
except ImportError:
    letter = None

def generate_citations(
    title: str, 
    authors: List[str], 
    year: Optional[int], 
    journal: Optional[str] = None, 
    url: Optional[str] = None
) -> Dict[str, str]:
    """
    Generates bibliographic citation strings in APA, MLA, IEEE, Chicago, Harvard, and BibTeX formats.
    """
    # Author string formatting
    if not authors or authors == ["Authors Unspecified"] or authors == ["Authors unspecified"]:
        authors_str = "Unknown Author"
        first_author_last = "Unknown"
        bib_authors = "Unknown Author"
        ieee_authors = "Unknown Author"
    else:
        # Standard APA: LastName, F. M.
        formatted_auths = []
        for a in authors:
            parts = [p.strip() for p in a.split() if p.strip()]
            if len(parts) > 1:
                formatted_auths.append(f"{parts[-1]}, {parts[0][0]}.")
            else:
                formatted_auths.append(a)
        
        if len(formatted_auths) == 1:
            authors_str = formatted_auths[0]
        elif len(formatted_auths) == 2:
            authors_str = f"{formatted_auths[0]} & {formatted_auths[1]}"
        else:
            authors_str = f"{formatted_auths[0]} et al."
            
        first_part = [p.strip() for p in authors[0].split() if p.strip()]
        first_author_last = first_part[-1] if first_part else "Unknown"
        ieee_authors = ", ".join(authors)
        bib_authors = " and ".join(authors)

    year_str = str(year) if year else datetime.now().strftime("%Y")
    journal_str = journal if journal else "Academic Literature Database"
    url_str = url if url else ""
    
    # Generate clean BibTeX reference key
    first_word = title.split()[0] if title.split() else "paper"
    clean_word = re.sub(r'[^a-zA-Z0-9]', '', first_word).lower()
    bibtex_key = f"{first_author_last.lower()}{year_str}_{clean_word}"
    
    # APA
    apa = f"{authors_str} ({year_str}). {title}. *{journal_str}*."
    if url_str:
        apa += f" Retrieved from {url_str}"
        
    # MLA
    mla = f"{authors_str}. \"{title}.\" *{journal_str}*, {year_str}."
    if url_str:
        mla += f" <{url_str}>."
        
    # IEEE
    ieee = f"{ieee_authors}, \"{title},\" *{journal_str}*, {year_str}."
    if url_str:
        ieee += f" [Online]. Available: {url_str}"
        
    # Chicago
    chicago = f"{authors_str}. \"{title}.\" *{journal_str}* ({year_str})."
    if url_str:
        chicago += f" {url_str}"
        
    # Harvard
    harvard = f"{authors_str} ({year_str}). {title}. *{journal_str}*."
    if url_str:
        harvard += f" Available at: <{url_str}>"
        
    # BibTeX
    bibtex = f"""@article{{{bibtex_key},
  author = {{{bib_authors}}},
  title = {{{title}}},
  journal = {{{journal_str}}},
  year = {{{year_str}}}"""
    if url_str:
        bibtex += f",\n  url = {{{url_str}}}"
    bibtex += "\n}"
    
    return {
        "apa": apa,
        "mla": mla,
        "ieee": ieee,
        "chicago": chicago,
        "harvard": harvard,
        "bibtex": bibtex
    }

def export_as_markdown(title: str, sections: Dict[str, Any]) -> str:
    """Combines key-value pairs or text chunks into a Markdown string."""
    md = f"# {title}\n\n"
    md += f"*Generated by PaperLens on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n\n---\n\n"
    
    for heading, content in sections.items():
        md += f"## {heading}\n\n"
        if isinstance(content, list):
            for item in content:
                md += f"- {item}\n"
        elif isinstance(content, dict):
            for key, val in content.items():
                md += f"**{key}**: {val}\n\n"
        else:
            md += f"{content}\n"
        md += "\n"
        
    return md

def export_as_text(title: str, sections: Dict[str, Any]) -> str:
    """Combines research outputs into clean plain text."""
    txt = f"{title.upper()}\n"
    txt += f"Generated by PaperLens on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    txt += "=" * 50 + "\n\n"
    
    for heading, content in sections.items():
        txt += f"--- {heading.upper()} ---\n"
        if isinstance(content, list):
            for item in content:
                txt += f"* {item}\n"
        elif isinstance(content, dict):
            for key, val in content.items():
                txt += f"{key}: {val}\n"
        else:
            txt += f"{content}\n"
        txt += "\n"
        
    return txt

def export_as_docx(title: str, sections: Dict[str, Any]) -> bytes:
    """Generates a styled Microsoft Word document from research sections."""
    if not docx:
        raise ImportError("python-docx is not installed in the environment.")
        
    doc = docx.Document()
    
    # Title
    t = doc.add_paragraph()
    r = t.add_run(title)
    r.font.name = 'Arial'
    r.font.size = Pt(22)
    r.bold = True
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Metadata footer
    p_meta = doc.add_paragraph()
    r_meta = p_meta.add_run(f"Exported by PaperLens - {datetime.now().strftime('%B %d, %Y')}")
    r_meta.italic = True
    r_meta.font.size = Pt(9)
    p_meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph()  # Spacing
    
    # Add sections
    for heading, content in sections.items():
        h = doc.add_heading(heading, level=2)
        h.style.font.name = 'Arial'
        h.style.font.size = Pt(14)
        h.bold = True
        
        if isinstance(content, list):
            for item in content:
                doc.add_paragraph(str(item), style='List Bullet')
        elif isinstance(content, dict):
            p = doc.add_paragraph()
            for key, val in content.items():
                r_key = p.add_run(f"{key}: ")
                r_key.bold = True
                p.add_run(f"{val}\n")
        else:
            doc.add_paragraph(str(content))
            
        doc.add_paragraph()  # Separator spacing
        
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream.getvalue()

def export_as_pdf(title: str, sections: Dict[str, Any]) -> bytes:
    """Generates a professional PDF document from research sections using ReportLab."""
    if not letter:
        raise ImportError("ReportLab is not installed in the environment.")
        
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter, 
        rightMargin=54, 
        leftMargin=54, 
        topMargin=54, 
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        name='PDFTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#0F172A'),
        alignment=1, # Center
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        name='PDFSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        leading=12,
        textColor=colors.HexColor('#64748B'),
        alignment=1,
        spaceAfter=30
    )
    
    heading_style = ParagraphStyle(
        name='PDFHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#1E293B'),
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        name='PDFBody',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155'),
        spaceAfter=8
    )
    
    list_style = ParagraphStyle(
        name='PDFList',
        parent=body_style,
        leftIndent=20,
        spaceAfter=4
    )
    
    story = []
    
    # Title
    story.append(Paragraph(title, title_style))
    # Subtitle
    story.append(Paragraph(f"Exported by PaperLens - {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
    
    for heading, content in sections.items():
        story.append(Paragraph(heading, heading_style))
        story.append(Spacer(1, 4))
        
        if isinstance(content, list):
            for item in content:
                # Bullet structure
                bullet_text = f"&bull; {item}"
                story.append(Paragraph(bullet_text, list_style))
        elif isinstance(content, dict):
            # Table layout or line by line
            for key, val in content.items():
                item_text = f"<b>{key}</b>: {val}"
                story.append(Paragraph(item_text, body_style))
        else:
            # Clean paragraph replacements
            text_lines = str(content).split("\n\n")
            for line in text_lines:
                if line.strip():
                    # Clean line breaks
                    clean_line = line.strip().replace("\n", "<br/>")
                    story.append(Paragraph(clean_line, body_style))
                    
        story.append(Spacer(1, 10))
        
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
